server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    language-service:
      path: /service/**
      service-id: language-service

  ignored-services: /*